import type { Config } from "tailwindcss";

export default {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "#fbf8fc",
        foreground: "#1b1b1e",
        primary: "#b90538",
        "on-primary": "#ffffff",
        "primary-container": "#dc2c4f",
        "on-primary-container": "#fffbff",
        "primary-fixed": "#ffdadb",
        "primary-fixed-dim": "#ffb2b7",
        "on-primary-fixed": "#40000d",
        "on-primary-fixed-variant": "#92002a",
        secondary: "#505f76",
        "on-secondary": "#ffffff",
        "secondary-container": "#d0e1fb",
        "on-secondary-container": "#54647a",
        "secondary-fixed": "#d3e4fe",
        "secondary-fixed-dim": "#b7c8e1",
        "on-secondary-fixed": "#0b1c30",
        "on-secondary-fixed-variant": "#38485d",
        tertiary: "#006947",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#00855b",
        "on-tertiary-container": "#f5fff6",
        "tertiary-fixed": "#6ffbbe",
        "tertiary-fixed-dim": "#4edea3",
        "on-tertiary-fixed": "#002113",
        "on-tertiary-fixed-variant": "#005236",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "surface": "#fbf8fc",
        "on-surface": "#1b1b1e",
        "surface-variant": "#e4e1e6",
        "on-surface-variant": "#5b4041",
        outline: "#8f6f71",
        "outline-variant": "#e3bdbf",
        "inverse-surface": "#303033",
        "inverse-on-surface": "#f3f0f4",
        "inverse-primary": "#ffb2b7",
        "surface-bright": "#fbf8fc",
        "surface-dim": "#dcd9dd",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f6f2f7",
        "surface-container": "#f0edf1",
        "surface-container-high": "#eae7eb",
        "surface-container-highest": "#e4e1e6",
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      fontFamily: {
        sans: ["var(--font-jakarta)", "var(--font-sans)"],
        heading: ["var(--font-jakarta)", "var(--font-heading)"],
        jakarta: ["var(--font-jakarta)"],
      },
    },
  },
  plugins: [],
} satisfies Config;
